---
output:
  bookdown::pdf_document2:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Note this section is Required -->

\doublespacing

The following individuals certify that they have read, and recommend to the Faculty of Graduate
and Postdoctoral Studies for acceptance, the dissertation entitled:

\vspace{5mm}


\noindent\underline{\makebox[6in][l]{Convergence and Conflagration: Wildfires and Shifting Landscapes in the Cache la Poudre Canyon}}  
\vspace{2mm}

submitted by \underline{Maya Daurio} in partial fulfillment of the requirements for

the degree of \noindent\underline{\makebox[5in][l]{Doctor of Philosophy}}  

in \noindent\underline{\makebox[5.8in][l]{Anthropology}}

\vspace{5mm}

**Examining Committee:**

\noindent\underline{\makebox[6in][l]{Dr. Mark Turin, Anthropology and Institute for Critical Indigenous Studies, UBC}}  
Supervisor

\noindent\underline{\makebox[6in][l]{Dr. Tracey Heatherington, Anthropology, UBC}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{Dr. Andrew Martindale, Anthropology, UBC}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{Dr. Sara Shneiderman, Anthropology, UBC}}  
Supervisory Committee Member 

\noindent\underline{\makebox[6in][l]{Dr. Gastón Gordillo, Anthropology, UBC}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Dr. Lori Daniels, Forest and Conservation Sciences, UBC}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Dr. Kim Fortun, Anthropology, University of California, Irvine}}  
External Examiner

<!-- Committee members that did not attend the defence -->
**Additional Supervisory Committee Members:**

\noindent\underline{\makebox[6in][l]{Name of your Committee Member}}  
Supervisory Committee Member
