---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Remember, It can't be longer than 350 words! -->

High severity wildfire and post-fire flooding can dramatically alter landscapes and disrupt people's lives, sometimes in complex ways not readily visible to the broader public or to the naked eye. Wildfires in the western U.S., and elsewhere in the world, are becoming more destructive for communities and ecological systems. In response to the changes in how wildfires are affecting our communities and environments over roughly the last two decades, this research explores how people are reorienting to transformed lives and landscapes and coping with loss as a result of wildfire. Drawing on over two years of situated, ethnographic fieldwork in a wildfire-impacted landscape, I ask: how do people understand their own lives and experiences within the different timescales and lifecycles of human and more than human ecologies in the formation of wildfire? What capacity do we have to make sense of affective and ecological transformations wrought by wildfire and post-fire flooding? How do institutional and policy responses to wildfires shape people’s relations with different forms of governance and the environment? How do such responses affect the capacity of people to make decisions about their lives and futures? I explore these questions through an anthropological exploration in the landscapes of the upper Poudre Canyon in northern Colorado. My research highlights three main arguments. First, in mountain watersheds, we can anticipate social consequences resulting from wildfire by examining the ecological disturbance cascade it initiates. Second, state-sponsored efforts to cultivate best practices for living with wildfire risk should be more geographically and socially expansive, to acknowledge that contending with wildfire and its associated hazards of smoke and flooding is a society-wide challenge. Third, people experience a recalibration of relationship to place from engaging in processes of sensemaking in response to extreme wildfires and resultant landscape changes. This dissertation contributes to a more than human anthropology by attending to the qualities of fire and flood as they exist in a processual and relational material world through sustained ethnographic engagement with people and place.
