---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This section is optional -->

I am, first and foremost, grateful for the opportunity to be a doctoral student, to have spent much of the last five years of my life engaged in the privileges of learning, reading, and writing. My return to graduate school, in the middle of an established career, was always motivated by a desire to be a student in pursuit of knowledge again, and I am grateful for how meaningful the arc of this pursuit has been for me.

The process of obtaining a PhD is hardly a solitary endeavor. I have been guided, supported, and encouraged along the way at various stages by a network of caring and insightful individuals, to whom I would like to express my profound gratitude. Primary among them is my supervisor, Dr. Mark Turin. His writings on the relationship between linguistic and biological diversity in the context of Nepal inspired my Master's thesis research in 2008. In 2017, I was fortunate enough to participate in a panel he moderated at a Himalayan Studies conference, and it was this experience which prompted me to apply to pursue a PhD under his supervision. Never in my academic life have I felt so set up to succeed, so supported, nor felt so imbued with faith in my scholarly potential as I have studying under Mark's supervision. Mark opened door after door for me: connecting me to GIS job opportunities at UBC; writing me into grants which provided professional development, research experience, financial assistance, and co-authorship opportunities; hiring me in different capacities to work on enriching engagements, including as a Teaching Assistant for his course *FNEL 180: Introduction to Endangered Language Documentation and Revitalization*; and encouraging my development as a writer and thinker by guiding me through the wonderful world of co-producing knowledge and co-authored publishing.

As a student seeking feedback or requesting a letter of support for a grant application, Mark was incommensurably responsive, kind, generous, and insightful. Even after I changed my dissertation research topic two years into my doctoral program to a geographic location and subject matter as far from my original focus on Nepal and language as could be, Mark, and all of my remarkable Supervisory Committee members, provided their full support. This research shift had no bearing on Mark's unflagging advocacy for my research and engagement with my writing. I am ever grateful for the opportunity to have pursued a PhD under his guidance.

I am deeply appreciative of my supportive and engaged Supervisory Committee who offered astute and meaningful input on my research and writing. Dr. Tracey Heatherington, whose background in environmental anthropology I deeply benefited from, provided discerning feedback throughout my dissertation, in particular encouraging me to dig deeper into the lineage of certain concepts and to connect literature across theoretical approaches. I am grateful for her kindness and encouragement. I had the honor of both working for Dr. Andrew Martindale, providing GIS support for a conceptually fascinating archaeological research project, and being the recipient of his rich and expansive insight into methodological and theoretical aspects of my work. As the lone archaeologist on my committee, Andrew provided critical guidance on pursuing a three article dissertation and pointed me toward relevant literature transcending the arc of my cultural anthropology background. At the same time, I am grateful for his deep provocations on ethnographic work and considerations of larger cultural constructs. Dr. Sara Shneiderman is an editor extraordinaire, whose perceptive, actionable feedback highlighted everything from grammar errors to chapter structure and relevant scholarship in which to situate my work. I benefited greatly from her input drawing on her own transdisciplinary, multi-sited, and collaborative scholarship. She helped identify thematic connections across global disaster anthropology that enriched the significance of my research findings. I am a better scholar because of Sara's generative and generous insight.

In the Poudre Canyon, I am thankful for the generosity and kindness I experienced throughout my time living there, and for all the meaningful conversations about shared experiences of loss and change. My deepest gratitude to all who welcomed me into their homes, entrusted me with their stories, gave of their time and expertise, and enhanced my knowledge and understanding about risk, sense of place, and impermanence. I have the utmost admiration for my fellow volunteer firefighters with the Poudre Canyon Fire Protection District. My experiences taught me so much about the implications of living in a rural, mountainous area, the spectrum of hazards with which we all contend, cross-jurisdictional governance, about generosity of spirit, and life and death and dignity.

Hiking across debris flow deposits, between the skeletal trunks of ponderosa pine, and moving through streambeds alongside scientists and practitioners represent the halcyon days of my fieldwork. These excursions opened up new worlds, and I'm grateful to all who let me tag along and entertained my many questions. Thank you to all who generously shared their expertise, experiences, and perspectives with me. I continue to learn from your work.

I am grateful to Colin Barry, Dr. Daniel Godwin, Jan Gueswel, Corrina Marshall, Dr. Camille Stevens-Rumann, Shayla Triantafillou, Dr. Ellen Wohl, and the many dedicated people with the Coalition for the Poudre River Watershed, the Larimer Conservation District, and the Arapaho and Roosevelt National Forests for presenting your work, coordinating watershed and fuels treatment tours, and otherwise engaging with the upper Poudre Canyon community.

One of the mysteries of graduate school is the persistent experience of feeling as though one is the first person to have ever navigated the numerous requirements and procedures in the process of obtaining a PhD. I would have been entirely lost without the time, feedback, expertise, and documentation provided by my fellow graduate students at UBC. The prolonged interruption of the COVID-19 pandemic six months into my PhD program, which prevented in-person interactions for some time, did not diminish the support and guidance provided by my colleagues, to whom I owe a great debt of gratitude. Thank you to Stephen Chignell, Byron Arthur Clark, Raphaël Deberdt, Anudeep Dewan, Patrick Dowd, Jonathan Eaton, Vicki Sear, Lara Şarlak, Eric Simons, Kawin Tiansuwan, Bendi Tso, Caitlyn Yates, and many others.

I am grateful for the financial support provided by the Social Sciences and Humanities Research Council of Canada through the Vanier Canada Graduate Scholarship and the Explore Research Assistantship Grant; P.E.O. International; the Social Science Research Council of the United States through the Rapid-Response Grants on Covid-19; the UBC Public Scholars Initiative and Climate Emergency Fund; the UBC Four-Year Fellowship; the Esri Canada GIS Scholarship; Dr. Marianne Ignace, and the Anthropology Graduate Studies Committee.

I deeply appreciate the engaging and financially supportive employment, research, and mapping opportunities provided by numerous individuals and organizations during my time at UBC, including by Dr. Marnyi Gyatso, Dr. Daniel Heath Justice, Dr. Andrew Martindale, Dr. Dana Powell and Dr. Rebecca Witter with the Environmental Justice Co-Lab, Dr. Leslie Robertson, Evan Thornberry and others at the UBC Research Commons, Dr. Bendi Tso, Dr. Mark Turin, and the wonderful people with the Community Engaged Documentation and Research (CEDaR) cluster.

I am grateful for the diverse research engagements throughout my PhD (many facilitated by my supervisor Dr. Mark Turin) and the opportunity to work alongside and learn from scholars including Tyler Baley, Jag Bahadur Budha, Dr. Stephen Chignell, Lily Clarke, Dr. Sienna Craig, Dr. Colin Grier, Nawang Tsering Gurung, Dr. Daniel Kaufman, Jason Lampel, Sophia Linn, Dr. Ross Perlin, Lucas Roy, Dr. Selma K. (“Sam”) Sonntag, and Dr. Tamara Wall. My heartfelt thanks to Dr. Sarah McCaffrey, Dr. Pasang Sherpa, Dr. Serbulent Turan, P.E.O. Chapter D of Whitefish, and Taylor Greenup for your engagement with and support of my work.

In Vancouver, my deepest gratitude to Gyata Sandoval for creating and providing such a beautiful refuge for Wilbur and me, and for your kindness and generosity in helping me weather the pandemic and graduate school in general. Thank you to Raphael Sandoval, Camila Fernandez, and Hannah Avenant for your kindness toward and care of Wilbur.

I am fortunate to have always felt supported and encouraged by my parents, Jane Abbott and John Daurio, in all my endeavors, and I've enjoyed commiserating with my mother throughout my doctoral program regarding the parallels between our experiences. I am grateful to all of my grandparents, Kate and Scott Abbott and Antoinette and Philip Daurio, for their love, validation, and curiosity about and engagement with the world from which I draw my inspiration.

My success at UBC would have been impossible without the careful coordination and support of the staff in the Department of Anthropology facilitating graduate students in overcoming all the administrative hurdles we must navigate. Thank you, too, to the maintenance and cleaning staff, performing critical and often invisible work that makes it possible for us to occupy the spaces we do.
