---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
link-citations: true
linkReferences: true
bibliography: ./References/living.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction

"Living with fire." "Live Wildfire Ready." "Fire Adapted Communities." These are some of the common catchphrases that presently dominate messaging about wildfire to the American public [@brenkert-smithLivingWildfirePark2023; @LiveWildfireReady; @tomanSocialScienceWildlandurban2013]. Most people in the U.S. will be familiar with the persistent mascot of the United States Forest Service (USFS), Smokey Bear, and his message, "Only You Can Prevent Wildfires". These phrases reflect dominant narratives in the wildland fire practitioner and management community and signify how the public, and particularly those people who live in fire adapted landscapes, are supposed to understand and navigate their relationship with wildfire. What does living with fire mean, to the agencies promoting these ideas, and to the communities toward whom this messaging is directed? What does it look like to facilitate living in a world where the impacts from wildfires affect people and places across jurisdictions for many years after the wildfire itself?

In this paper, I address these questions in the context of a rural community in northern Colorado called the Poudre Canyon, which was one of sixteen communities impacted by the 2020 Cameron Peak Fire (CPF), the largest in Colorado state history. Drawing on ethnographic research conducted over more than two years, I argue that we need to broaden our conceptualization of what it means to live with wildfire to include hazards which often accompany it, such as wildfire smoke, flooding, and debris flows. This would help communities better prepare for the multiple hazards associated with wildfire, and also assist policymakers and governments to identify infrastructure gaps for integrated response. Attending to multiple hazards represented by wildfire also expands our understanding of the geographies of risk, facilitating a shift in focus to include not only communities who live in fire adapted landscapes but also those potentially impacted by smoke and the downstream effects of wildfire-impacted watersheds. Wildfire &mdash; and the smoke, heat, and floods which accompany it &mdash; affects everyone, not just those who live in landscapes that burn. Harnessing the language of living with fire,[^1] I propose moving beyond current framing of "personal responsibility" and instead understanding people who live in fire adapted landscapes as potential stewards rather than agents of increased risk. Recognizing that the concept of stewardship is contested and how it is operationalized can allocate authority to some and not others [@walkerWhoseLandscapePolitical2003], I follow conceptualizations that define stewardship as a process [@conradHumanSocialDimensions2017] that is relational [@kimmererBraidingSweetgrassIndigenous2013; @hellerIncludingStewardshipEcosystem2023] and centers care for both the human and more than human world, and agency for communities living in fire adapted landscapes [@pecanhaenqvistStewardshipBoundaryObject2018].

I challenge the utility of the term wildland urban interface (WUI) to delineate geographies of wildfire risk because it creates homogenizing assumptions about communities in the WUI which hinders effective wildfire risk communication and reduction. I show how many people in the Poudre have a broad understanding of the multiple risks involved in living in a mountain environment, of which wildfire risk is but one consideration. Living with fire is a process, and I argue those who study, reside, and work in fire adapted landscapes, are undergoing a period of recalibration in response to more extreme wildfires and their associated hazards.

## Narratives Around Wildfire Risk

The policy focus on living with or adapting to fire is easy to understand. In many areas around the world, including the U.S., Canada, Mediterranean Europe, and Australia, wildfires are increasing in size, frequency, and severity due to a combination of climate change, forest management, and land use factors [@coopExtremeFireSpread2022; @wassermanClimateInfluencesFuture2023; @turnerMagnitudeDirectionTempo2022; @mathewsWildfiresGhostsPathogen2021; @parksContemporaryWildfiresAre2023; @castellnouEmpoweringStrategicDecisionmaking2019]. At the federal level in the U.S., this reality is characterized as a wildfire crisis in several publications [@forestserviceConfrontingWildfireCrisis2022; @WildfireCrisisLandscape2022; @swainEraMegafiresCrisis2018; @BidenHarrisAdministrationLaunches2023] whose narratives reflect a broad understanding that more destructive wildfires interfacing with our built environments are inevitable, so communities and society need to prepare to experience wildfire.

In the U.S. these narratives are delineated by certain phrases, such as "defensible space," the "Home Ignition Zone (HIZ)", or "personal responsibility" [@coloradostateforestserviceHomeIgnitionZone2021; @coloradostateforestserviceProtectYourHome], all directed at preparing individual homeowners who live in the WUI, to perform wildfire risk reduction efforts around their properties. The WUI is defined by the Colorado State Forest Service (CSFS) as an "area where structures or other human developments meet or intermingle with wildland vegetation or fuels" [@LarimerCountyWildfire]. Research has shown removing vegetation in the vicinity of homes and altering houses to make them more resistant to fire can be effective at reducing wildfire risk [@cohenWildlandurbanInterfaceFire2008; @maranghidesWUIStructureParcel2022]. Focusing on wildfire mitigation around homes is therefore a sensible strategy by the fire management community to promote risk reduction. However, the ways in which guidance regarding mitigation is communicated to homeowners and the general public is premised on a number of assumptions, which I suggest are ultimately harmful to the strategic goals of reducing wildfire risk in communities.

### Reexamining the Wildland Urban Interface and the Personal Responsibility Narrative

The WUI is a catch-all term to describe an ever expanding area in the U.S. [@radeloffRapidGrowthUS2018; @carlsonWildlandUrbanInterface2022; @mockrinGrowthWildlandurbanInterface2022]. Frequently characterized as the "Wildland Urban Interface fire problem" [@cohenWildlandurbanInterfaceFire2008; @mellWildlandUrbanInterface2010; @maranghidesFrameworkAddressingNational2013], more homes in the WUI is an oft-cited reason for the increase in exposure of communities to wildfire [@hawbakerChangesWildfireOccurrence2023; @weiEstimatingWUIExposure2023; @barrettWildlandUrbanInterfaceProblem2021; @calkinHowRiskManagement2014]. A newspaper article discussing Colorado's three largest wildfires in 2020, explains, "As the Wildland Urban Interface grows, so is the risk of larger and more destructive fires..." This implies, simplistically, that the size and severity of wildfires can all be explained by the contemporaneous growth of the WUI, growing at a similar rate, with the same levels of exposure everywhere. It erases the historical context for why we are increasingly experiencing more extreme wildfires today &mdash; including climate change, Indigenous land dispossession, and federal forest management which suppressed fire for over a century &mdash; while placing the blame on individual homeowners who *choose* to put themselves in harms way. The question of choice in residential location is complicated by many factors, among them affordability, work [@schirmerRoleLocationResidential2014], and a housing shortage to the tune of four to seven million homes [@horowitzSurveyFindsLarge2023]. Furthermore, nearly any location where people reside  will be exposed to some kind of natural hazard, whether fire, flooding, extreme heat, or earthquakes [@NationalRiskIndex2023]. 

While it is important to recognize the impact of housing growth in areas more prone to wildfire occurrence, most discussions of the WUI and the homes within it contribute to an idea of *the* WUI; that is, a homogeneous zone where all communities are similarly geographically situated and with uniform levels of risk and housing growth. This hypothetical WUI is typically conceptualized as a forested landscape in the western U.S. near federally managed lands on which the density of homes is ever increasing. In reality, communities who live in what I prefer to call fire adapted landscapes are diverse, located throughout various geographic regions across the country, and have differing levels of risk, home distribution, density, and growth [@maranghidesWUIStructureParcel2022]. A recent study, for example, found that more homes are exposed and destroyed by wildfires in grasslands and shrublands than in forests [@radeloffRisingWildfireRisk2023].

Much of the living with fire literature directed at homeowners in areas traditionally associated with the WUI is characterized by an emphasis on individual responsibility [@coloradostateforestserviceHomeIgnitionZone2021; @petersonFireAdaptedCommunities2016] for reducing wildfire risk on private property. Some of the literature also makes the assumption that homeowners expect the government, and in particular, the federal government, to save their homes from wildfire. In the Home Ignition Zone guide published by the CSFS, it states:

> **As more people choose to live in wildfire adapted areas, additional homes and lives are potentially threatened every year**. Firefighters always do their best to protect residents, but **ultimately, it is your responsibility to protect your property and investments from wildfire** [@coloradostateforestserviceHomeIgnitionZone2021, my emphasis].

In an otherwise insightful article by some leading thinkers about wildfire, the authors commend the efforts of a county wildfire mitigation program in part because it "...builds wildfire resiliency from the bottom up and **helps temper the expectation that the federal government is exclusively responsible for community protection**" [@calkinWildlandurbanFireDisasters2023, my emphasis].

In the book *Living with Fire*, the authors repeat the narrative about the perceived responsibility of the federal government to protect a small number of Americans while contradicting themselves elsewhere by stating that large numbers of people live in the WUI (p. 47):

> By putting the protection of private property ahead of other management concerns, we effectively manage our vast tracts of public wilderness for the benefit of a relatively few residents of the wildland-urban interface [@jensenToolsLivingFire2008, 105].

The specific language of "personal responsibility" in relation to homeowners reducing wildfire risk also appears in a homeowner guide from the National Interagency Fire Center [@ReadySetGo] and is enshrined in language from Colorado Senate Bill 22-007 in its direction to fund the Live Wildfire Ready program:

> While homeowners and property owners in Colorado bear the ultimate responsibility to prepare their homes and property for wildfire, many still do not understand this responsibility, the risk they face living in the wildland-urban interface, or the necessary steps to reduce their wildfire risk [@leclairLiveWildfireReady2023].

The CSFS takes the personal responsibility narrative one step further, suggesting that people need to "accept responsibility for living in an area with wildfire hazards" [@petersonFireAdaptedCommunities2016].

I do not mean to suggest that all fire practitioners espouse these exact narratives, nor to discount the important risk reduction efforts and support for communities at various levels of government and among nonprofits in Colorado, even if some of these entities harness similar kinds of narratives in their work. Rather, I hope this contribution enhances the effectiveness and relationship-building capacities of these entities in their engagements with different communities throughout Colorado in relation to wildfire.

### An Overview of the Literature on Wildfire Risk Perception

The origins of and reasons why the personal responsibility narrative is so pervasive may be linked to a broader cultural shift, from a conception of collective risk following the New Deal, to the assignment of risk to the individual in subsequent decades [@collierNeoliberalismNaturalDisaster2014]. This aligns with the neoliberal paradigm of resilience in the context of risk management, where personal responsibility may be seen as a proxy for resilience. This approach institutionalizes the mobilization of individuals to take responsibility for their own welfare while they are at the same time overseen within "a sphere of governance"[@josephResilienceEmbeddedNeoliberalism2013]. 

There has been considerable research into individual and community risk perception of wildfire and flooding, which does not find conclusively that people lack responsibility or perceive that the federal government should be responsible for mitigating risk, nor does the literature suggest messaging personal responsibility to individual homeowners as an effective strategy in risk reduction efforts. Some studies directly contradict these narratives, showing the majority of residents understand wildfire risk to their homes, and do not expect the government to mitigate risk on private property [@mccaffreyOutreachProgramsPeer2011; @brenkert-smithLivingWildfirePark2023].

What the literature on risk perception and attitudes toward mitigation does show is that there is considerable heterogeneity in how individuals and communities perceive risk and responsibility, even of the same wildfire event [@edgeleyCharacterizingDivergentExperiences2022]. Perceived risk may not be the same across hazards. Previous experience with flooding, for example, may be a good predictor of individual and collective flood mitigation action [@burnettFactorsInfluencingFlood2023], whereas previous experience with wildfire results in more variable perceptions of future risk [@martinRoleRiskPerceptions2009; @ghasemiExaminationSocialpsychologicalDrivers2020]. A number of studies suggest that risk exposure, the reasons people live in the places they do, and how they perceive wildfire mitigation by different actors varies according to cultural, geographic, institutional, historical, and land use factors [@mccaffreyUnderstandingPublicPerspectives2007; @brightContextBeliefsAttitudes2007; @edgeleyCharacterizingDivergentExperiences2022]. Results from this extensive literature over nearly two decades point to the importance of localized context in understanding risk and social dynamics and adaptive capacity [@mccaffreyUnderstandingPublicPerspectives2007; @paveglioUnderstandingSocialImpact2015; @paveglioExploringSocialCharacteristics2012] and in establishing trust and acknowledging local values [@vaskeSalientValueSimilarity2007].

The literature does not seem to support the efficacy of messaging personal responsibility in reducing risk nor the need to impugn people for where they choose to live, the reasons for which are complex. A fire adaptation strategy which conceptually separates &mdash; with judgement &mdash; those who choose to live in the WUI from those who do not is shortsighted for a number of reasons. First, different kinds of hazards exist everywhere. Just because someone does not live in the WUI does not mean they are not exposed to other kinds of hazards. Following the CPF, for example, when sediment transport facilitated through flooding compromised downstream water quality and supply, it was the populations in cities largely thought to be outside the WUI who were vulnerable.

Second, it may be necessary to expand our idea of what constitutes the WUI and who lives there. A year after the CPF, the state's largest fire by acreage, Colorado suffered its most destructive wildfire, which began as a grass fire and spread into suburban neighborhoods, burning over 1,000 homes mostly surrounded by low density vegetation in less than a day, along with a Tesla dealership, and damaged several big box stores surrounded by impervious surfaces [@chulahwatImpactWindCharacteristics2024; @swainDeadlyDynamicsColorado2022].

Third, the personal responsibility narrative conceptually isolates wildfire risk to the fire itself, obscuring the risks associated with wildfire smoke, which are usually much more widely geographically distributed [@wilmotExpandingNumberWestern2021]. A recent study estimates that more than 50,000 deaths in California between 2008 and 2018 are attributable to fine particulate matter from wildfire smoke [@connollyMortalityAttributablePM22024]. Extreme heat, rarely geographically isolated, sometimes accompanies and exacerbates wildfire risk and spread [@ruffaultIncreasedLikelihoodHeatinduced2020]. Flooding is another risk associated with wildfires in forested watersheds, the impacts from which can also impact communities many miles downstream from where the wildfire occurred, not only those in the WUI.

Finally, this narrative masks the ways that people who live in the WUI may contribute to risk mitigation. The personal responsibility narrative precludes the opportunity to cultivate relationships between communities and fire practitioners which mobilize residents as invested partners in addressing multiple hazards related to wildfire. Rather than assuming people are not responsible, acknowledging the stewardship role communities can and may already be playing provides those communities with a sense of agency. Legislation accompanied by funding that supported the agency of WUI residents would help wildfire mitigation efforts move beyond the — albeit important — home ignition zone to empower individuals and communities to more actively engage with fire management themselves, for example through prescribed burning. As previously mentioned, a persistent narrative is that communities in the WUI expect the federal government to protect them from wildfire [@calkinWildlandurbanFireDisasters2023]. Although expectations of professional firefighters vary by community [@brenkert-smithLivingWildfirePark2023], one way to temper expectations of the federal government to perform community protection is to expand fire management capacity beyond federal responsibility to include private landowners. This is not just my aspiration but is part of the mission of organizations like The Ember Alliance[^2] or the Fire Networks and is supported by some who work for the USFS, the dominant fire management agency at the federal level. One USFS employee who works in planning told me, "I think there's a degree of supporting people's self-determination and their kind of natural rights to use fire. Part of being fire adapted is being able to use fire as a tool, as a landowner, as an interested party, as a fire department, as a whoever."

Communication with homeowners in the WUI could benefit from reframing, moving away from a narrative of personal responsibility to a language of shared stewardship. This language is already being used to some degree in grey literature, and in scholarship on flood mitigation[@kooistraInstitutionalizingUnitedStates2022; @burnettFactorsInfluencingFlood2023], but it is not typically the language used in wildfire risk reduction literature aimed at homeowners nor, from what I observed, in face-to-face interactions with community members. It would be beneficial to fire management, to communities in the WUI, and to all of society if policymakers recognized those particular communities who live near federal lands as potential stewards and supported their existing self-mobilization towards living safely with fire. I offer examples and evidence from ethnographic research in the Poudre Canyon to support my arguments.

## Study Area 

The upper Poudre Canyon is an unincorporated community in Larimer County in northern Colorado, west of Fort Collins, the largest nearby city. Just under half of Larimer County's population lives in the WUI [@LarimerCountyWildfire]. This study area was chosen for several reasons. First, the landscape and its people were heavily affected by the CPF, including persistent wildfire smoke exposure, long evacuations &mdash; up to seventy-three days &mdash; large-scale loss of forests, and structure loss. Beginning in 2021, the first year after the fire, and persisting through 2024, the upper Poudre has also experienced damaging and catastrophic flooding and debris flows. A debris flow in the Black Hollow drainage, one of thousands of tributaries to the Poudre River, killed four people and destroyed six homes in July 2021.

Second, it is a quintessential WUI community in the sense that it is entirely surrounded by forested public lands (the Arapaho-Roosevelt National Forest), but it does not align with other assumptions about the WUI, specifically the idea of ever-expanding housing development. It therefore offers an instructive lens through which to highlight the importance of understanding the local context of each community's circumstances when addressing wildfire challenges, as earlier scholarship suggests [@mccaffreyCommunityWildfirePreparedness2015; @paveglioCategorizingSocialContext2015; @yadavIncreasingWildfiresChanging2023].

For the census tract corresponding most closely to the upper Poudre Canyon, the population decreased between the 2010 and 2020 censuses, even while a neighboring census tract, also rural, increased in population (though only by 170 people) [@20102020Census2022]. There are few families with children in the upper Poudre, and the one-room schoolhouse was closed by the school district in 1994 due to low numbers of enrollment. Many, if not the majority, of the residents in the upper Poudre are 65 and older.

Coincident with declining population growth, new development is limited. This is in part due to topographic constraints on building sites because of the steep canyon walls. Also, 85\% of land along the river corridor belongs to the federal government, primarily the USFS [@CachePoudreWild1990], and new commercial development is limited by Larimer County.

Development has waxed and waned since the mid-1800s, following the expulsion of the area's Indigenous inhabitants by the state, who included the Nunt'zi (Ute), Hinono'eino' (Northern Arapaho), Tsistsistas (Cheyenne), NeI (Shoshone), and Paneassa (Pawnee) &mdash;  [@burrisPeoplePoudreEthnohistory2006]. Colonial settlement in Colorado, as across the western U.S., was encouraged through the Homestead Act of 1862 [@EarlySettlements] to promote agriculture, mining, and trade and attract non-Indigenous settlement in the valley [@burrisPeoplePoudreEthnohistory2006]. For the upper Poudre, existing settlements, or what are now viewed as incursions into the WUI, can be directly traced back to a concerted effort by the federal government to encourage population expansion in this area. A number of homes in the upper Poudre are over a hundred years old, and some of them precede the establishment of a national forest in 1908 in the Poudre Canyon [@HistoryCulture]. Historic homes were among those that burned in the upper Poudre, including a home and outbuildings dating to the 1880s belonging to my family. The area with the largest population density in the upper Poudre used to be a ranch and was subdivided in the 1960s, the last significant spate of development in this part of the canyon.

A one-size-fits-all WUI narrative does not accurately characterize each community facing wildfire risk. For the upper Poudre, increasing settlement in the WUI is not what contributes to greater wildfire exposure. Contributions may include the legacy of fire suppression on USFS lands allowing fuel to build up, climate change, and the dispossession of Indigenous peoples who may have conducted periodic burning, especially in valley bottoms [@bakerIndiansFireRocky2002]. From 1905, when the USFS was established as an agency, until 1978, it executed a policy of complete fire suppression [@vanwagtendonkHistoryEvolutionWildland2007], altering fire adapted ecosystems. Operationally, since then, it has been difficult for the USFS to move beyond an overemphasis on fire suppression [@butlerUSFireLearning2010; @northReformForestFire2015] in part because they are tasked both with restoring fire adapted ecosystems while limiting wildfires which endanger lives or property [@pietruszkaConsequentialLightningcausedWildfires2023] and contending with competing fire management mandates across state and federal jurisdictions [@schultzCollaborationsCapacitiesTransform2019].

In the entire Poudre Canyon, there are 750 full-time and 1,500 part-time residents, but it draws over 500,000 recreational visitors a year [@Us2024]. The Poudre River parallels Highway 14 for nearly fifty miles as it flows along the contours of steep, forested slopes and rocky outcrops, supplying water for hundreds of thousands of people in the populous Front Range cities of Fort Collins and Greeley. The Poudre Canyon's two main population centers are divided between the lower and upper canyon, forty minutes apart by car. In 2012, the High Park Fire swept through the lower Poudre and nearby communities, destroying 259 homes. In 2020, the CPF burned over much of the upper Poudre, lasted nearly four months, and became the state's largest wildfire in a year during which the three largest wildfires in Colorado occurred [@BennetWelcomes792022].

The Poudre River watershed drains around 1,889 square miles in the Poudre Canyon alone, and in populated areas of the Poudre, some of the river's thousands of miles of tributaries pass through private lands, often in their lowest reaches before reaching the river. The largest numbers of people continue to be based in proximity to creeks or on flat lands where early settlers could ranch, mine, or extract timber, which was sent down the river during the years 1868 to 1885 to use as railroad ties [@evansCachePoudreNatural1991]. This topography, formed by thousands of years of geologic movement, combined with land use and ownership established over shorter timescales, help shape the way people in the Poudre Canyon experienced two large wildfires and the post-fire flooding following these wildfires.

These patterns of settlement in the geography of the Poudre Canyon may benefit larger risk reduction and recovery efforts, as I will describe further in the Results section of this paper. This is due in part to the role private landowners can play in collaborating with other stakeholders to implement efficient mitigation strategies when these may not be available to a large agency like the USFS, which is beholden to different mandates.

## Methods

This paper is based on ethnographic research engaging with the situated, temporal complexities [@mcgranahanWhatEthnographyTeaching2015; @graizbordExpertDayTheory2017; @jusionyteThresholdEmergencyResponders2018; @herbertEthnography2000] of how humans are affected by wildfires and associated hazards. Research methods included participant observation, semi-structured interviews, walking interviews, and the go-along method, explained in more detail below.

### Participant Observation

For over two years from June 2022-October 2024, I lived in the upper Poudre Canyon and participated in activities such as social events, community association and fire board meetings, and site visits to private property and USFS lands impacted by wildfire or flooding. I joined the Poudre Canyon Fire Protection District (PCFPD) as a volunteer, which is a small, entirely volunteer-run fire district, operating over the length of the canyon and beyond. The PCFPD facilitates the use of the river corridor and its surrounding national forest lands by 500,000-800,000 visitors a year, responding to vehicle accidents, medical emergencies, and attending to abandoned campfires, lightning strikes catching something on fire, or a burning vehicle alighting surrounding vegetation. The PCFPD helps residents with chipping and pile burning of woody debris generated by removal of vegetation by homeowners around their homes to reduce their wildfire risk. In collaboration with Larimer County, PCFPD assesses homes for wildfire risk at homeowners' requests, generates a report for the homeowner, and applies for grants to assist homeowners with wildfire mitigation. PCFPD first responders make the Poudre River corridor, hiking trails, and surrounding areas, safer places to study, fish, paddle, camp, drive, hike, or climb. Over many years, more community members than not have volunteered their time and services to the fire district, either as first responders or on the fire board. Others serve the PCFPD by making meals for monthly firefighter trainings. Services provided by the PCFPD benefits not only the Poudre Canyon community but all who move through it and make use of the river and surrounding public lands.

### Interviews

I conducted fifty semi-structured interviews with different stakeholders, including community members, wildland fire, emergency and watershed management practitioners, and scientists whose studies intersect with ecological, geological, or social aspects of wildfire, post-fire flooding, or recovery. Of these, twelve also included open-ended conversations while walking in the CPF burn scar or accompanying researchers doing scientific fieldwork, a kind of walking interview [@evansWalkingInterviewMethodology2011; @carpianoComeTakeWalk2009]. I also used go-alongs [@kusenbachStreetPhenomenologyGoEthnographic2003], a qualitative research method offering a "relational perspective on place and space" [@carpianoComeTakeWalk2009: 263] to accompany three different teams of scientists &mdash; fluvial geomorphologists, biogeochemists, and geologists &mdash; in six wildfire-impacted watersheds during their fieldwork, and thirteen scientists and fire/watershed managers within areas of the CPF burn perimeter. I identified participants by meeting them at community events, conferences, and other events, through literature reviews, and snowball sampling. Interviews with both community members and subject-matter experts consisted of open-ended questions loosely organized around how participants were making sense of the CPF and everything that came after it. Interviews were primarily conducted in person, with twelve conducted over Zoom and one over the phone, and lasted between 45 minutes and two hours. All except six interviews were recorded and transcribed, and all were coded in NVivo. I refer to participants with pseudonyms.

## Results

In this section, I discuss four aspects of living with fire in the Poudre Canyon. First, residing in the Poudre facilitates ongoing relationships to the land, and to fire, forests, and water. Second, collaborations with private landowners on watershed recovery after the CPF point to the potential role of landowners as stewards in mitigating different kinds of risk. Third, the PCFPD responds to and helps mitigate a broad spectrum of hazards, including wildfire, providing services which benefit the local community, recreational visitors, agencies, and populations downstream. The widespread involvement of community members with the fire district over time cultivates a broad understanding of the risks associated with living in a rural, mountainous landscape like the Poudre, risks which include but are not limited to wildfire. Fourth, at the same time, my findings show people across the three interview groups need time to adjust to living in an era with more extreme wildfire, what the historian Stephen Pyne calls the Pyrocene [@pyneWelcomePyrocene2021], or the age of fire, characterized by wildfires and subsequent watershed responses which defy what most people have previously experienced in their lifetimes. Below, I examine these four elements of living with fire and argue that they contribute to a stewardship framework as a basis for cultivating fire adapted communities.

### Rootedness in Place

"Well, lovey, does it look like four feet to you?" Richard asked, referring to the diameter of a 500-year-old ponderosa pine which had been killed in the CPF. We were trying to eyeball how big it actually was. Richard and his sister Char, who together run the only remaining lumber mill in the vicinity of the Poudre Canyon, had stopped by my family's property in October 2023 to see how the CPF had affected the land, which the two siblings had known since they were children. "I hate to see a big tree like that die," Richard said.

People who live in the Poudre have a close relationship to forests and fire. Because there is no natural gas line up the Poudre Canyon and electricity and propane are expensive, many people collect firewood each year to use in their woodstoves for heat, either from USFS lands, their own lands, or from neighbors’ lands. One family hosts a communal firewood cutting day, and in the aftermath of the CPF, people have gathered to help neighbors clean up hazard or fallen trees.

Residents use local toponyms to refer to prominent geographic features, and some families have their own toponyms for places of significance to them, names which do not appear on any map, such as The Old Man’s Face or The Spire. These names root people in place over time. The Silent Forest, for example, is a section of forest off of a USFS trail far enough from the nearby creek that one cannot hear it, known by this name by multiple generations of just one family which lives nearby. Places are imbued with meaning because they evoke memories of experiences, people, and events of the pasts, *and* because of their present materiality [@bassoWisdomSitsPlaces1996].

The intimacy of the connection which people in the Poudre Canyon have to the landscape in which they live demonstrates an investment in and attention to the health of that environment, developed through attachment to place through the process of settlement over time, what may be termed "settlerism" [@johnsonSettlerSensibilitiesEnvironmental2023]. The acknowledgement of these local connections, histories, and knowledges by fire, forest, and emergency managers could facilitate relationship building with local residents toward the creation of shared goals in adapting to smoke, fire, and floods in the environment of the upper Poudre.[^3]

### Post-fire Stewardship

Watershed recovery, implemented in collaboration with private landowners, resulted in time-sensitive work and benefited a wide geographic area and population base extending far beyond the Poudre Canyon, a form of emergent stewardship following the CPF. Below, I explain how this work provided protective benefits for residents in the Poudre who were exposed to flooding after CPF, and how it also continues to benefit the much larger populations in Fort Collins and Greeley who rely on the Poudre River for drinking water, as well as the hundreds of thousands of recreational visitors to the canyon each year who swim, paddle, and fish in the river.

As of August 2024, flooding has occurred every summer on tributaries of the Poudre River, resulting in life and structure loss and impacting private lands and property, county and state roads, acquatic life, and water quality of the Poudre River. Watersheds subjected to wildfire can experience changing hydrological and geomorphological conditions making them more susceptible to flooding or debris flows [@rengersLandslidesWildfireInitiation2020]. Wildfire also increases the availability of sediment that can be transported downstream and changes the biogeochemical composition of water with implications for water quality [@wilsonConnectivityPostfireRunoff2021; @sanchezPhysicalBiogeochemicalDrivers2023; @rhoadesLegacySevereWildfire2019; @hohnerWildfiresAlterForest2019]. In the upper Poudre, the vast majority of tributaries to the Poudre River originate on USFS land, and at least eight of these empty into the river on private lands, such as Black Hollow Creek. Following the CPF, watershed restoration was a high priority for a wide range of stakeholders.

In the summer of 2021, the Natural Resource Conservation Service (NRCS), a federal agency under the U.S. Department of Agriculture (USDA), made Emergency Watershed Protection (EWP) funds available to perform flood mitigation work on private lands in the Poudre Canyon. The NRCS is empowered to support work on private lands, whereas the USFS, which is also part of the USDA, is not. Larimer County and the City of Greeley, the latter which holds water rights to much of the Poudre River for its drinking water and was a municipal sponsor for the EWP funds, split the burden of overseeing EWP-funded flood mitigation geographically. The local government sponsor typically provides a 20\% match to the EWP funds, but in this case, the Colorado Water Conservation Board (CWCB) provided the match on behalf of Greeley. The Coalition for the Poudre River Watershed (CPRW) helped coordinate watershed recovery efforts and located supplemental funding from the Colorado Department of Public Health and Environment (CDPHE) for additional mitigation work. A consulting company was hired to design and implement flood mitigation for those areas overseen by Greeley, whereas the county’s own engineers performed this work where they were responsible. Because Greeley has a vested interest in the water quality of the Poudre River, the consulting company designed flood mitigation to protect private property and also catch sediment before it reaches the river. The involvement of CPRW and the interest of CDPHE in funding flood mitigation reflect the value placed on watershed health and its impacts on all who live in that watershed, including downstream water users.

A number of tributaries in the upper Poudre and surrounding areas which pass through private lands also happen to represent some of the most widely and severely burned watersheds, including at their headwaters. A research biogeochemist with the USFS told me that these are indicators of how much potential these tributaries have to negatively contribute to poor water quality of the river. Installing sediment retention structures on these tributaries as soon as possible after the CPF was important in protecting downstream water quality as well as private roads, homes, and bridges. I was told most of this work done in the summers of 2021, 2022, and 2023 was on private property, not only for the purposes of protecting assets on private lands but because it was easier, less time-consuming, and less restrictive to coordinate with private landowners than the USFS, which has prohibitive permitting requirements. In some cases, access to these tributaries was facilitated via private bridges over the river, without which these lower reaches would be inaccessible. That the majority of watershed recovery work has occurred on private lands is also reflected in an online project map put together by CPRW [@CameronPeakFire2022].

It may be worth exploring other multi-jurisdictional, multi-agency collaborations with private landowners in preparing for and recovering from wildfires in different WUI, land ownership, and watershed contexts. This case study demonstrates that the presence of and collaboration with private landowners living in proximity to USFS lands in post-fire watershed recovery positively impacted watersheds, private landowners, and geographically diverse sections of society.

In the next section, I describe another way in which people in the upper Poudre are active stewards in mitigating risk with benefits for a much broader population base and geographic area.

### Living With and Mitigating Risks

We were a motley crew of volunteer firefighters from different departments, some with kitted out wildland firefighting backpacks, others with fire shelters attached through our belt loops and small plastic water bottles stuffed into the pockets of our Nomex (fire resistant) pants. Our group was responsible for curtailing the progression of the south flank of the Stove Prairie Fire which had started that afternoon in a dry wash riddled with trash and various kinds of shooting targets, including golf balls, bowling pins, plywood, and clay pigeons. In this wash used as an unofficial shooting range, some people had inadvertently started a fire on this windy, dry April day when their bullets caused a spark (see Figure 1).

In rural, unincorporated communities around the state of Colorado, local, volunteer fire districts are the first line of defense against wildfires as well as other hazards. Perhaps because of the aforementioned widespread community involvement with the PCFPD, most community members understand the multiple risks associated with living and recreating up the Poudre, from rockfall on the narrow canyon highway to trees falling on cars at a national forest campground (see Figure 2). Rather than bucking responsibility related to living in the WUI, people up the Poudre have nuanced understandings of the complex ecosystem of risks involved in living there, of which residing in a fire adapted landscape is but one consideration. Furthermore, PCFPD volunteers, and the wider community of earlier volunteers, are assets to a wide range of stakeholders and land managers because of their presence and service in a landscape where the jurisdiction of responding to emergencies or wildfires would otherwise fall entirely to the county or to the USFS, whose employees live in Fort Collins, up to three hours away from the areas to which PCFPD responds.

### *There's going to come a day when Colorado's going to catch on fire*

Back before 2012, the Arapaho-Roosevelt National Forest was known as the "asbestos forest" to wildland firefighters based out of Fort Collins because it never seemed to burn. People in the Poudre spoke about small wildfires they had previously experienced which were quickly put out, and there is a record of wildfires in the general area dating from 1893 [@fryCachePoudreRiver1954; @schneiderForestFiresPoudre2020]. The 2012 High Park Fire was the first wildfire with devastating consequences for the Poudre Canyon, including evacuations, loss of homes, and subsequent flooding. Most of these impacts were felt by lower canyon residents because the wildfire never entered the upper portion of the canyon, although it affected access and shaped expectations throughout the Poudre Canyon about the future possibility of destructive fire.

At the time, the PCFPD fire chief lived in the lower Poudre. He and his wife had moved to the Poudre in 2008 from California, where he had been a career structural and wildland firefighter. The High Park Fire began on June 8, 2012 and was contained by July 1, 2012, before the onset of the summer monsoon in Colorado, characterized by frequent afternoon thunderstorms usually beginning in July and lasting into August [@NorthAmericanMonsoon2023]. Based on his wide-ranging experiences with wildfire in California, Chris, the fire chief, expected that flooding from tributaries that burned would occur during the summer. He asked the Larimer County Office of Emergency Management for sandbags in anticipation but was told "It doesn't flood here. This is a different kind of soil than in California."

As Chris predicted, when the monsoon began, the tributaries began flooding and damaging homes, and the county did eventually provide sand and bags to be filled. Later they even provided an automated sandbag filler, which Chris would fill with sand using his tractor. At first, it was up to the community to fill the bags, and Chris again used his prior experience to help properly fill bags and place them to deflect water effectively. Even those in the community who did not need sandbags jumped in to help. "I mean, it just doesn't happen like that in L.A.," Chris explained.

These experiences during the High Park Fire point to the learning curve that comes with living with fire, by government agencies and the public alike. In 2013, heavy rains resulted in a swollen Poudre River which primarily impacted Fort Collins with extensive flooding, through which lower reaches of the Poudre River flow. The 2013 floods jumpstarted a number of watershed coalitions &mdash; including CPRW &mdash; along the Front Range through funding provided by a Community Development Block Grant for disaster recovery through Housing and Urban Development (HUD). These back-to-back disasters in 2012 and 2013 shaped how individuals and various government agencies perceive wildfire and flooding and respond to it today. For many in the upper Poudre, PCFPD firefighters notwithstanding, the kind of extreme fire behavior, high burn severity, and massive acreage that characterized the CPF eight years after High Park and which dramatically altered the landscape in which they live was not something they had intimately experienced before. The 2012 High Park Fire was the first major wildfire to dramatically impact the canyon, but even it did not burn for as long, affect as much acreage, or burn at such high levels of severity [@HighParkFire2012]. I heard from multiple community members in the upper Poudre that they always associated flooding risk with the main stem of the Poudre River, not with its tributaries. This was informed by either knowledge of an 1891 dam breach which caused a catastrophic flood on the Poudre or of the Big Thompson Flood of 1976 in a neighboring canyon which killed 144 people. People in the upper Poudre had rare experiences with flooding on tributaries. Black Hollow Creek, which turned into the tragic debris flow in 2021, was mostly a babbling brook over the course of sixty years during which one of the Black Hollow residents had observed it. The debris flow changed the way people understand the relationship between fire and flood and the potential for much smaller watersheds to present the greatest danger of flooding.

At the 2023 Colorado Wildland Fire Conference, some fire and watershed practitioners and scientists expressed incredulity that landowners who were informed the tributaries near their homes were likely to flood after the CPF did not believe it because they and their "father's grandfather" (to quote one of the scientists) had never experienced anything like it. However, I argue that it is reasonable to understand the capacity of a creek to behave in a certain way based on empirical observations collected over a lifetime and historical, situated knowledge passed down from one generation to the next. People who have experienced wildfire and who may be exposed to subsequent hazards like flooding need time and empathy to adjust to the rapidly changed realities of living in a post-wildfire landscape. Part of living with fire is living with altered environments, with cascading hazards, and in some cases, devastation.

Messaging directed toward those who live in fire adapted landscapes implies that people residing in these areas need to learn to live with fire. Yet the Poudre Canyon and its residents have been living with fire for a long time, recounted by multiple longtime residents. Volunteers with the PCFPD respond to a number of wildfires each year. It seems that what is actually meant is that people need to learn to live with catastrophic fire, as well as potentially destructive post-fire flooding. Policymakers and practitioners communicating with communities exposed to wildfire risk need to acknowledge existing relationships with fire and be explicit about what being a fire adapted community means in the context of extreme fires. I suggest that living with fire is not just about removing vegetation from around one's home. It's a process of recalibration in response to rapid, large scale, and ongoing changes to vegetation and hydrology [@daurioTemporalRecalibrationsLearning2023]. Living with fire is also about learning how to navigate complex bureaucratic and administrative systems during and after the fire and coping with loss. This loss may include loss of life, loss of a home, loss of control, or loss of sense of place.

Some of these impacts are not limited to those who live within the burn area. Just as wildfire smoke and water quality affect people far beyond the perimeter of the wildfire, so do the emotional and social dimensions of loss and change. The Fort Collins-based researchers and practitioners I interviewed experienced CPF on a deeper, more personal level because it was in their backyard, in their watershed, at their research sites, and in the places they like to recreate. As one person involved in wildfire policy and forest management for decades said about his colleagues, "People were really kind of wrecked in a lot of different ways. ...this is our watershed. This is a place where people have family histories, even people that moved here recently. The first thing they did was to go up and camp, hike, whatever they do. So, people have very strong personal place connections, sense of place for this whole area." Living with fire is a process, not an event, or a list of mitigation tasks to check off. And we are all of us &mdash; those who live in fire adapted landscapes, those who study fire adapted landscapes, and those who govern and manage them &mdash; engaged in a process of recalibration, often in response to a wildfire that impacts us personally.

## Discussion

This ethnographic case study reflects the circumstances of one community affected by wildfire and post-fire flooding and therefore embodies one set of options for how stewardship with private landowners can be cultivated. Other communities facing or already having experienced wildfire will have different perspectives and geographies. This research contributes to literature emergent from CPF and recent wildfires and offers a valuable perspective on how a rural community facilitates stewardship of both private and federal lands and the water that runs through them, and helps mitigate hazards to the benefit of populations outside the community. In addition to the examples I have provided from the Poudre, I advocate for more cross-jurisdictional partnerships with rural communities toward a shared goal of learning how to better live with fire. I argue that reconceptualizing communities residing in fire adapted landscapes as potential stewards opens up pathways for mobilizing these partnerships. It also centers agency for living with fire with communities. Below are several examples of what centering agency could look like.

A study on voluntary and regulatory wildfire risk reduction in two rural unincorporated communities in Wyoming and Utah showed a preference in these communities for greater local agency in implementing and managing wildfire mitigation [@edgeleySupportRegulatoryVoluntary2020]. There are good examples of this already happening. In California and a number of other states, for example, Prescribed Burn Associations (PBAs) are community-based, mutual-aid networks which support private landowners in burning on their own lands [@CaliforniaPrescribedBurn]. Organizations like the Fire Networks, The Ember Alliance, and Fire Adapted Colorado advocate for expanding agency over fire management to include local capacity [@zotero-10034; @EmberAllianceChanging; @FireAdaptedColorado]. A recent Fire Networks blog post suggested harnessing the ranching concept of "neighboring" for community wildfire mitigation initiatives [@burchfieldNeighboringAntidoteSeparation2024]. There is also emergent research examining the idea of community-based forestry on land owned by different landownership entities and suggestions for further research that examines opportunities for community-based wildfire risk management [@davisCommunitybasedForestryFederal2020]. Stewardship of lands which is co-created by multiple government and nonprofit actors reflects already existing federal goals for addressing wildfire governance [@FIREReportWildland2023]. Building on previous work, I encourage the added inclusion of private landowners in consideration of these objectives and in post-fire watershed management [@charnleyFosteringCollectiveAction2020; @kirklandTakingAlllandsApproach2021].

There is a concerted push on the part of county, state, and federal agencies to create fire adapted communities in order to contend with increasing wildfire exposure to properties and lives. Part of this advocacy is encompassed within messaging crafted by fire and emergency managers to reach those who live in the WUI. In this paper, I question the usefulness of using the term WUI because it homogenizes people, places, and local contexts of wildfire risk. It also geographically limits our perception of wildfire risk and separates how we think about and prepare for other wildfire-related hazards such as smoke and post-fire flooding, the impacts from which are felt far beyond the burn perimeter.

I advocate moving away from the narrative of personal responsibility as a strategy to encourage homeowners to undertake wildfire risk reduction efforts, as it is simply not supported by the literature or data on risk perception and homeowner action/inaction. This narrative also assigns liability to individual homeowners who live in the WUI and creates a false notion that only those who live in the WUI are subject to wildfire-related risks. In cultivating fire adapted communities, I think it is more helpful to characterize wildfire as something with which everyone in society has to contend, whether it is through direct contact with wildfires, wildfire smoke, or post-fire hazards such as flooding or compromised water quality. I argue that reshaping the narrative about those who live in fire adapted landscapes encourages a shift in perspective to understand the people in these communities as allies in cultivating the practice of living with fire. Centering co-stewardship opens up possibilities for collaboration and collective action that may otherwise be foreclosed. Approaching frontline communities as custodians allows us to center care for their well-being and that of the surrounding environment. 

## References

[^1]: See [@ottoliniKindlingChangeShaping2024] for a discussion similarly arguing for a new paradigmatic approach to living with fire, what they term "New Fire Culture."
[^2]: I am on the BOD for The Ember Alliance and a member of the Fire Networks.
[^3]: Much has been written about the deep connection to place among Indigenous communities the world over [@poudelPondBecomesLake2018; @asfawRoleSocialSupport2019]. My work highlights the place-attachment of a non-Indigenous community and suggests that policymakers should attend to the importance of such connections for all people in cultivating living with fire and in disaster recovery.

<!-- # References -->
\section*{Bibliography}
\addcontentsline{toc}{section}{Bibliography} 

<!-- Reset page config. For proper referencing  -->
\noindent
\leftskip=2em
\parindent=-2em

<div id="refs"></div>