---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
link-citations: true
linkReferences: true
bibliography: ./References/cascade.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Dale had just made himself a drink on the afternoon of July 20, 2021, when the power blinked on and off, and he heard what sounded like a shotgun blast. He later attributed the sound to the destruction of an electricity transformer. He looked outside to see a power pole swinging back and forth even though there was no wind and then noticed his patio was covered in about a foot-and-a-half of mud and water. As he futilely tried to get his patio chairs out of the way, all he could think was, 'Where is all this water coming from?' He put his rubber boots on and made his way up through the water to what he calls 'the shelf,' a flat area on a hill overlooking Black Hollow Creek which flows by the home his father built.

The creek had grown exponentially in size and volume and created a new channel. He watched in disbelief as one of his neighbor's homes floated away down the river. There were four people inside that home, all of whom died that day. Five other homes were destroyed, no vehicles could cross the bridge over the river for a week, and the land on which the remaining homes stood had been radically altered by the mass of trees and huge boulders deposited where houses used to be. These homes and the area immediately surrounding them at Black Hollow, as the settlement is known, had been spared in the 2020 Cameron Peak Fire (CPF). But it became a place of destruction and tragedy more than six months after the fire had been declared contained due to a massive debris flow, a phenomenon closely linked to wildfire as an ecological disturbance.

Wildfire can change the hydrological conditions of a watershed in ways that make it more susceptible to flooding or debris flows, in what is known as a cascading hazard [@hydeUncertaintiesPredictingDebris2016]. Based on my research in a community affected by the CPF, I show how cascading hazards have cascading consequences for people's lives and social structures writ large. I argue that drawing on existing ecological frameworks of the wildfire-flood disturbance cascade to interrogate the wildfire-social disturbance cascade enables the possibility of responding to wildfire in a way that explicitly links social-ecological systems. I propose that cross-disciplinary teams examine post-fire social-ecological conditions and conduct assessments over longer timescales to help coordinate long-term recovery efforts in response to cascading social and ecological consequences.

In geology, cascading hazards refer to a sequencing of processes, beginning with a primary hazard which precipitates the formation of additional hazards [@sharmaIncreasingRiskCascading2023]. This is also sometimes called a disturbance cascade [@nakamuraDisturbanceRegimesStream2000]. One example of an ecological disturbance with additional hazard potential, and the one germane to the subject of this paper, is a wildfire which leads to post-wildfire flooding and debris flows. In 2020, a year of record-breaking wildfire activity across the western United States [@rodmanHistoric2020Fire2022], the CPF funneled through the upper Poudre Canyon in northern Colorado on two days of extreme fire spread. This was followed by extensive flooding and debris flows in the summers of 2021, 2022, and 2023, including at Black Hollow.

The physical damage wrought by these intersecting disasters is well documented, and has been quantified in the number of structures destroyed, acres burned, or occurrence of debris flows. The CPF is Colorado's largest wildfire in state history encompassing 208,912 acres [@WFIGSInteragencyFire2023], which destroyed 492 structures across sixteen communities and three watersheds, including the Poudre, Big Thompson, and Laramie watersheds [@coalitionforthepoudreriverwatershedCameronPeakFire]. These kinds of statistics appear in research papers [@rodmanHistoric2020Fire2022], on state [@HistoricalWildfireInformation2024] and nonprofit websites [@coalitionforthepoudreriverwatershedCameronPeakFire], and in newspaper stories [@larsenCameronPeakFire2020; @DeadlyFlashFlood2021]. As such, numbers become the main way impacts from these hazards are narrated and understood by both the public and government officials. These quantifiable categorizations are typical of most disasters, characterizing them as 'temporary aberrations from normal conditions' [@fiskeSlowOnsetDisasterClimate2019, p. 139], the idea of which shapes frameworks of disaster response procedures in the U.S. Information about emergency response and recovery is similarly quantitatively understood and measured by, for example, acres burned at high severity, inventories of fish species at risk in burned areas [@fairchildFinalFisheriesSpecialist2020], or roads most vulnerable to flooding impacts [@larimercountyofficeofemergencymanagementCameronPeakFire2021]. These statistics provide critical information which can be measured against other wildfires and flooding events and offer a sense of both the scale and the number of people or communities who were or are exposed to risk.

Relying primarily on quantitative assessments, however, obscures the varied experiences of contending with multiple hazards, as well as the ongoing ways people's lives continue to be affected, cascading out from the wildfire, for years to come. Quantitative summaries of disaster can also be mobilized by those actors involved in governance who are fluent in the language of risk analysis to produce quantitative risk assessments which not only overshadow non-quantifiable discourses of uncertainty but also hold a strategic advantage in decision-making processes [@grovesBombMyBackyard2015].

Disaster anthropologists have shown that disaster survivors are uniquely positioned to reflect on the affective experience of the social and material consequences of disasters [@barriosGoverningAffectNeoliberalism2017; @oliver-smithTheorizingVulnerabilityGlobalized2004], and the same is true for those who have experienced wildfire and its associated hazards. The complex, sometimes unanticipated, lived experiences of wildfire are important to uncover and interrogate as a way to help better prepare individuals, governments, and society to plan for, respond to, and recover from a series of disasters propagating out beyond the start and end dates of the wildfire itself.

I suggest that in the context of the CPF, and arguably, in the context of most wildfires, there are ongoing and complex consequences for people's lives which cannot be easily enumerated and are therefore not as visible to nor considered by the public, policymakers, and fire and emergency managers. How do we account for, acknowledge, and respond to the complex circumstances of people's lives which result from living through a wildfire? What does recovery look like when we consider the breadth of experiences and account for longer time horizons in our response mechanisms? Focusing on narratives and perspectives emerging from ethnographic fieldwork in the Poudre Canyon, I harness the concept of cascading hazards to examine the accompanying cascading consequences affecting people in this mountainous area of northern Colorado following the CPF.

This article is organized as follows. First, I propose a conceptual framework of the social-ecological disturbance cascade for responding to wildfires. Second, I provide an overview of the literature on wildfire and disturbance in the social sciences and the anthropological approaches I draw on for this paper. Third, I describe my study site and the specific landscape characteristics which support a social-ecological perspective of disturbance. Fourth, I explain the methods I used for my research and why they are relevant for a landscape perspective of wildfire-related disturbance examining human and more than human relations. Fifth, I present and discuss results showing how cascading hazards resulting from wildfires have cascading consequences for people's lives. Finally, I reflect on the fire and emergency management and policy implications for utilizing a social-ecological disturbance cascade framework and propose one possible strategy for wildfire recovery in the future.

## Conceptualizing the Social-ecological Disturbance Cascade

The disturbance cascade involving wildfire and flooding is well known and oft-studied among those who research geological hazards such as landslides and debris flows [@rengersLandslidesWildfireInitiation2020; @staleyRecurrenceIntervalPostfire2020] or fluvial geomorphology, the study of the movement of rivers over time and how they shape landforms [@wohlBiogeomorphicInfluencesRiver2022]. Following a wildfire, there is an expectation among the scientific research and watershed management communities that there will be a disturbance cascade [@barnardWildfireClimateChange2023; @hohnerWildfiresAlterForest2019], and that post-fire conditions provide an opportunity to study the particular ways the disturbance cascade is enacted in specific watersheds [@gorrTriggeringConditionsRunout2023], which will vary based on a number of ecological, geomorphological, and anthropogenic factors.

Following the CPF and other large-scale wildfires, researchers have been studying changes to soil microbiome diversity [@nelsonWildfiredependentChangesSoil2022], the relationship between wildfire-induced changes in source water to downstream water supply and agricultural production [@barnardWildfireClimateChange2023], the role of large woody debris in post-fire debris flow sediment retention [@rengersInfluenceLargeWoody2023], analysis of post-fire conditions to guide reforestation management [@rodmanHistoric2020Fire2022], and how spatial heterogeneity in post-fire mountain watersheds influences the transport of sediment downstream [@wohlBiogeomorphicInfluencesRiver2022], among many other projects.

In contrast, in the social sciences, I am aware of only one research project related to community member experiences following CPF [@kooistraWebinarResidentsPerspectives2022] and one project assessing risk management tools during the fire [@caggianoCameronPeakFire2021].

There is no commonly used term to describe cascading hazards in the social sciences, even though there is a strong history of social science research on the human dimensions of wildfires, including the recognition of wildfire as having both ecological and social ramifications [@tomanSocialScienceWildlandurban2013]. I propose the term social-ecological disturbance cascade to delineate the explicit relationship between a wildfire, its ecological disturbance cascade, and the cascading consequences for people's lives it sets in motion. My research demonstrates that communities who suffer ongoing impacts from wildfires often experience them in ways connected to the ecological disturbance cascade and could benefit from an approach that mirrors some watershed-specific, longitudinal studies more common in ecological and geological research and restoration of post-wildfire conditions. Acknowledgement and understanding of social-ecological linkages in disturbances among those in positions of power, who formulate policy, and researchers of all backgrounds conducting wildfire and post-wildfire studies which inform policy and management decisions would stimulate and support more comprehensive future wildfire response and recovery efforts that are sensitive to the complex and ongoing needs of people living in wildfire-impacted areas.

Linking the study of ecological and social disturbance cascades facilitates an understanding of wildfire as a phenomenon shaped by and with implications for both ecological and social forces and enables the possibility of inclusive social-ecological responsiveness. Currently, at the federal level, preparation for and response to wildfire is logistically, financially, and administratively separated from preparations and responses associated with flooding caused by wildfires, and from wildfire smoke. Responsibility for these different phenomena is spread across multiple agencies operating under different mandates and with no clear pathway for cross-agency coordination. Wildfire management, including its prevention or reduction in its severity, is primarily the purview of the U.S. Forest Service (USFS). Wildfire smoke, on the other hand, which inevitably accompanies wildfires but can also be experienced by communities far from the source of the wildfire &mdash; such as the smoke engulfing New York City from Canadian wildfires in 2023 [@lowreyNewYorkFailed2023] &mdash; is managed by the U.S. Environmental Protection Agency (EPA). Research on post-fire flooding and debris flows is published by the U.S. Geological Survey (USGS), while funding for private property flood mitigation is often routed through the Natural Resource Conservation Service (NRCS), unless it is funded and directed instead under the purview of the Federal Emergency Management Agency (FEMA) in the event of federally declared disasters. States, counties, municipalities, fire districts, and nonprofits all interface with federal agencies in managing wildfire and post-fire watersheds in different ways.

This multi-jurisdictional but disunited management approach to the multiple hazards associated with wildfire and their implications for human lives results in disjointed preparedness. Readying the space surrounding one's home in order for the house to better withstand a wildfire does not prepare a homeowner to prevent excessive exposure to wildfire smoke. Similarly, post-fire recovery is multifaceted and jurisdictionally complex. Homeowners may be faced with a number of different challenges, including life-threatening flooding, road and bridge access or damage issues, insurance claims, home rebuilding and permitting processes, hazardous trees, slash (woody debris) build-up, emotional and physical distress, infestations of invasive plant and insect species, property damage from bears, rodents, or decomposing food during evacuations and power shut-offs, and reforestation needs. Any one of these issues may be managed alternately by different federal, state, or county agencies or nonprofits or not managed by any jurisdiction at all. There may be resources and funding available for a short period to address certain challenges such as the sandbags provided by the Larimer County Office of Emergency Management (OEM) the first summer following the CPF in 2021 but not for subsequent flooding events in the summers of 2022 and 2023. These challenges may occur simultaneously or years apart from each other, highlighting the need for a pathway to recovery built in response to anticipated and unanticipated, or simply cascading, social-ecological disturbances over multiple timescales and jurisdictions. A pathway which includes funding mechanisms to address wildfire-related preparation, response, and recovery over a longer timeframe, accounts for cross-jurisdictional complexity, and provides a central hub of resources and support would reduce the navigational hurdles with which those confronting multiple hazards over a number of years have to contend.

## An Overview of Wildfire and Disturbance in the Social Sciences

Earlier and ongoing wildfire-related social science research in anthropology, sociology, geography, and other disciplines across the globe has focused on fire and land management [@charnleyDiversityForestManagement2017; @zaharaBreathingFireLandscapes2020; @essenImprovingWildfireManagement2023], wildfire mitigation [@mccaffreyUnderstandingWildfireMitigation2020; @nicoleRiskPerceptionsMitigation2021; @meldrumRethinkingCostsharePrograms2024], suppression [@calkinNegativeConsequencesPositive2015], fuels treatments [@mccaffreyPrescribedFireWhat2006; @millerBarriersEnablersPrescribed2020], on risk perceptions related to wildfire [@weisshauptNorthernInlandWest2007; @cohnWildlandUrbanInterfaceResidents2007], smoke [@haglerEditorialUnderstandingCommunicating2021], and flooding [@burnettFactorsInfluencingFlood2023; @calkinHowRiskManagement2014], wildfire preparedness [@mccaffreyCommunityWildfirePreparedness2015; @jakesImprovingWildfirePreparedness2007], communication [@taylorInformingNetworkImproving2007; @christiansonCanadianWildfireCommunication2011; @kumagaiCausalReasoningProcesses2004], individual and community wellbeing following wildfires [@burnsIntegrativeHealingImportance2007; @carrollFireGalvanizingFragmenting2005], and considerations for future research in assessing the social impacts of wildfire [@paveglioUnderstandingSocialImpact2015]. Among social scientists studying wildfire, there is broad recognition that wildfires have wide-ranging social impacts beyond that which can be captured by statistics. Compared to other disasters such as hurricanes or floods, research on the ways wildfires impact specific communities over time is less common, and ecological consequences may be easier to characterize than social ones [@kentSocialEconomicIssues2003].

The concept of disturbance has also previously been leveraged to characterize wildfire impacts on people's lives. A compendium of wildfire-related social science research findings identifies wildfire as a social as well as ecological disturbance with both tangible and intangible impacts for people's lives [@tomanSocialScienceWildlandurban2013]. Writing more generally about disasters as disturbances, Hodgson advocates for institutionalized sense-making as a pathway for community adaptation to the impacts of disasters [@hodgsonEmotionsSenseMaking2007].

#### Anthropological Approaches to Disaster, Landscape, and Time

In spite of multidecadal research related to wildfire across disciplinary fields in the social sciences that has come to inform fire and emergency management strategies, the way we understand, prepare for, and respond to wildfires more generally continues to artificially separate social and ecological disturbances and their consequences over different timescales and across multiple jurisdictions. Anthropological scholarship identifies the temporal inscriptions [@adamsMarketsSorrowLabors2013] and social lives of disasters [@sorensenSocialLifeDisasters2015], which, through various cultural processes, expand beyond the timeframe and physical perimeter of the disaster itself.

Anthropologists have encouraged the consideration of materialist conceptualizations of time and space [@mooreAnthropoceneAnthropologyReconceptualizing2016], particularly in relation to the Anthropocene, the term proposed to signify a new geological epoch characterized by human-driven actions and processes. Whatever criticisms there may be of the term Anthropocene [@millingtonHimalayanBuddhismHuman2024], attending to the way human materialities and temporalities intersect with more than human material and temporal formations and processes requires us to conceptualize 'an expansive ecology of time' [@widgerMonsoonUncertaintiesHydrochemical2020] which transcends a human-centered idea of history [@chakrabartyAnthropoceneTime2018] and the 'complex conjunctures' [@mooreAnthropoceneAnthropologyReconceptualizing2016, p. 36] of the spaces of the Anthropocene. Following Tsing and coauthors, who propose that anthropologists engage with landscape to study how human and beyond human relations are structured relative to each other [@tsingPatchyAnthropoceneLandscape2019], I use the post-wildfire landscape of the Poudre Canyon to understand the conditions of social and ecological disturbances resulting from the CPF and reverberating over time in response to each other. Situated ethnographic fieldwork over longer time horizons more typical in anthropology can illuminate narrative experiences of wildfire and its cascading consequences over time and help make sense of the ways in which these experiences are often connected to or exacerbated by the ecological disturbance cascade.

## Study site 

As I describe in this section, the Poudre Canyon constitutes a landscape conducive to cascading geological hazards resulting from wildfire. There are 750 full-time and 1,500 part-time residents [@Us2024]. The Poudre River parallels Highway 14 in the canyon for approximately forty miles as it flows along the contours of steep, forested slopes and rocky outcrops, supplying water for the hundreds of thousands of people in the populous Front Range cities of Fort Collins and Greeley. The Poudre Canyon's two main population centers are divided between the lower and upper canyon. In 2012, the High Park Fire swept through the lower Poudre and several nearby communities, destroying 259 homes. In 2020, the CPF burned over much of the upper Poudre and fifteen other communities in Colorado over nearly four months. My own family's historic home, and that of our neighbor's, located in the upper Poudre, were the first two houses to burn in the fire, an experience which initiated this research inquiry.

The river corridor itself is made up of 85% federal lands, with only 2,000 out of 25,000 acres in private ownership [@CachePoudreWild1990]. The lands beyond the corridor are primarily owned by the USFS. Private lands are primarily situated along the river where flatter ground makes it easier to build, hemmed in by the canyon's steep, rocky mountainsides, carved out by a glacier in the uppermost sections of the canyon, or by the river, below the glacier's end moraine. Many, if not all, of these flatter pieces of land were formed either by alluvial fans, an accumulation of sediments that fans outward at the point where a steeper gradient meets a less steep gradient, or because they are part of the river's old floodplain. The Poudre River watershed drains around 1,889 square miles in the canyon alone, although the river continues east as it flows out of the canyon, 125 miles in total until its confluence with the South Platte River on the eastern plains of Colorado. In populated areas of the Poudre, some of the river's thousands of miles of tributaries pass through private lands, often in their lowest reaches before reaching the river. Most early settlers, and where the largest numbers of people continue to be based, built in proximity to a creek and prioritized settling land where they could ranch, mine, or extract timber, which was sent down the river during the years 1868 to 1885 to use as railroad ties [@evansCachePoudreNatural1991]. This topography, formed by thousands of years of geologic movement, combined with land use and ownership established over shorter timescales, help shape the nature of the consequences which people in the Poudre experienced over the course of two large wildfires and in the years following these wildfires.

The Poudre is officially composed of three unincorporated communities [@LarimerCountyColorado2024]. Larimer County, and its Board of County Commissioners with three elected officials, is the defacto governing body for all unincorporated communities, although the Poudre Canyon Fire Protection District (PCFPD) is a local governmental entity whose jurisdiction for emergency response and wildfire management encompasses the entire populated length of the Poudre Canyon [@Us2024]. Post-CPF recovery coordination was divided geographically in the Poudre Canyon between the City of Greeley, which has water rights to the Poudre River, and Larimer County. City of Greeley coordinated watershed recovery west, or upstream, of a bridge called Crown Point, and Larimer County was responsible for the areas east of this, or downstream.

## Methods

I used ethnographic research methods to investigate how cascading hazards resulting from the CPF have cascading consequences for those affected by the wildfire. Ethnography is able to capture the situated, temporal complexities of how humans are affected by wildfires and associated hazards [@mcgranahanWhatEthnographyTeaching2015; @jusionyteThresholdEmergencyResponders2018].

### Participant Observation

From June 2022 to October 2023, I lived in the upper Poudre and participated in activities such as social events, community association and fire board meetings, and site visits to private property and USFS lands impacted by wildfire or flooding. I joined the PCFPD as a volunteer and learned about how the fire district operates in relation to other agencies, such as the USFS and Larimer County Emergency Services. I attended conferences on wildland fire and natural hazards, joined educational tours and citizen science initiatives coordinated by local nonprofits, and participated in chipping and burning slash for neighbors.

### Interviews

I conducted fifty semi-structured interviews with community members, wildland fire, emergency and watershed management practitioners, and researchers whose studies intersect with ecological, geological, or social aspects of wildfire, post-fire flooding, or recovery. Of these, twelve also included open-ended conversations while walking in the CPF burn scar or accompanying researchers doing scientific fieldwork, a kind of walking interview [@evansWalkingInterviewMethodology2011; @carpianoComeTakeWalk2009]. In addition to interviews, I also used the go-along method [@kusenbachStreetPhenomenologyGoAlong2003] to accompany three different teams of researchers &mdash; fluvial geomorphologists, biogeochemists, and geologists &mdash; in four wildfire-impacted watersheds during their fieldwork, and seven scientists and fire/watershed managers within areas of the CPF burn perimeter. I identified participants by meeting them at community events, conferences, and other events, through literature reviews, and snowball sampling.

My premise, reflected in the experiences of those I interviewed and the conditions I observed, is that wildfire initiates a series of ongoing, cascading impacts on people's lives, captured through sustained research presence and engagement with community and expressed through narratives.

## Categories of Consequences

In this section, I examine the different social consequences emerging from the 2020 CPF in the upper Poudre Canyon, showing that 1) social impacts on people's lives can be categorized to capture the broad range of cascading experiences resulting from the original disturbance of the wildfire; 2) while social and ecological disturbances can occur in a kind of feedback loop, tracing ecological disturbances can help us anticipate social ones; and 3) the social-ecological disturbance cascade will be different for each community affected by wildfire but can be used to inform future scenarios for communities which have not yet experienced wildfire.

According to the measures typically used to account for how destructive a wildfire is, the upper Poudre fared reasonably well. Of the 492 structures destroyed in CPF, which lasted for 112 days, fewer than twenty were in the upper Poudre, which was the closest community to the wildfire and experienced two days of rapid fire growth over a month apart, affecting different sides of the canyon. Of the structures lost in the Poudre, none were primary homes, nobody died in the wildfire, including firefighters, even though it occurred during the COVID-19 pandemic, which complicated firefighting efforts and evacuations. These numbers, while important, do not contain within them the many ways people’s lives were disrupted by the wildfire that are essential for thinking through how to help other communities in the future respond to and recover from wildfire. Below, I provide some examples of social disturbance cascades, many of them linked to disturbances on the landscape.

### During the Fire

One couple in the upper Poudre was evacuated from their home the day the fire started just after stocking their refrigerator with groceries from Fort Collins. They were only able to return to their property seventy-three days later, after living in a hotel room with two cats. By the time they were permitted to return home, they had to replace their kitchen floor and their refrigerator on account of the food which had melted and rotted onto the floor when the power was shut off. One of their neighbors fared worse because his home was broken into multiple times by a bear who smelled the decomposing food and wreaked havoc throughout the house. The damage was so extensive he had to hire a contractor, who turned out to be corrupt. When I interviewed the neighbor about his experiences, he said:

> You know, in a lot of ways, the fire was the end at the same time that the fire was the beginning. It's tough when I think about it and I get emotional still, I get very upset. What I grew up with and what was inculcated into my being about the woods and the wilderness and the animals and the views and a sense of belonging to all that. The fire ended that. And while I'm appreciative of the little oasis, I'm still devastated when I drive through the burn scar. So the fire was the end. But then the fire is also the beginning, like the forest floor coming back and wildlife returning. But it also was the beginning, the catalyst for all these subsequent events. The bear wouldn't have been in here if the fire hadn't burned through, and he wasn't distressed and hungry. If I hadn't evacuated and stuffed everything in the freezer thinking I'm gonna be back in a few days. And then the power gets shut off, and all of a sudden the cabin reeks, and he has a smorgasbord for four days. Never would have happened. If that hadn't happened, I never would have had to hire this jackass of a contractor. And he wouldn't have destroyed my house and done more damage than the bear did.

Under normal circumstances, the presence of wildlife is often awe-inspiring for Poudre Canyon residents and one of the reasons people enjoy living there. During and in the years since the wildfire, however, residents have encountered some animals in unusual ways: multiple break-ins from bears, sometimes at strange times, like the night of the Black Hollow debris flow in one of the surviving homes; extreme mice infestations in a home evacuated for a short time; packrats which had previously nested in a workshop which burned down moved into the house which survived; and a black widow infestation where none of these spiders had been seen before over multiple generations. Some of these impacts are short-lived, like the mice infestation, whereas others are persistent, like the packrat nests. These multispecies encounters [@ogdenAnimalsPlantsPeople2013], in their myriad forms, are one of the unaccounted-for categories of the consequences of wildfire.

It is worth noting that when it comes to people's interactions with wildlife following the wildfire, not all have been negative. In the summer of 2023, an ecologist pointed out mating Lewis's Woodpeckers on my family's land in an area she said they would not have found habitat before the fire. Two people interviewed in 2023 observed that wildlife seems to be thriving after the wildfire based on their observations, more twin moose calves and fawns and more abundant and diverse wildlife sightings in general. This may point to another kind of opening when we connect social and ecological circumstances in examining wildfire's impacts. People's experiences and perceptions of ecological conditions in the Poudre help shape how they make sense of wildfire, of a changed and changing landscape, of the beginnings and ends of things and how they feel about them.

### After the Fire

For the people who did lose homes or other buildings to the wildfire, it set in motion its own series of cascading impacts, which are specific to this experience, in the form of loss of sense of place [@schlosbergDisasterPlaceJustice2020; @maldonadoCooccurringAccumulatingDisasters2018], complicated insurance claims, regulations which did not exist when the original constructions were built, obstructions from the county permitting office, being underinsured and therefore unable to afford to rebuild, lack of reliable access to the homesite due to ongoing flooding or erosion issues, or inability to rebuild in the same location for similar reasons, all of which were realities for people who lost homes in the Poudre. One couple I interviewed who rebuilt their house themselves said they were assigned eight different insurance claims agents in a process they described as 'belittling.' Another family still has not been able to rebuild as of the summer of 2024 because parts of the road to their land are continually being eroded or obstructed from flooding off the steep channels on an adjacent mountainside.

Six more families lost their homes in the Black Hollow debris flow, and four people their lives, a tragic illustration of how the wildfire (that caused no immediate loss of life) then initiated an ecological disturbance cascade with devastating repercussions for the people whose lives intersected with it. We can trace other repercussions by following the flow of water. The centeredness of the river in this physical and cultural landscape draws our attention to particular human and other than human material relations and conveyances of risk, where the river reflects “the cumulative historical effects” [@wohlVirtualRiversLessons2001, p. 7] of everything in its basin. Many people must cross bridges over the river to get to their homes. Where historically the river was the central focus of mining and was used to transport logs for railroad ties, now it is what draws hundreds of thousands to the canyon each year for recreation. And in the first summer after the wildfire, it collected bodies, homes, logs, boulders, and sediment in a debris flow event, choking out fish, undermining two bridges, and affecting water supply storage systems in two downstream major population centers dozens of miles away.

Most people in the Poudre Canyon get their drinking water from wells. It is the hundreds of thousands of people living in the northern Colorado cities of Fort Collins and Greeley &mdash; and the municipal water managers for these cities &mdash; who have to contend with the water quality impacts to the Poudre River due to sediment transport from all the tributaries. The recently retired water manager for the City of Greeley told me in June 2023 that the city had to shut off their Poudre River water intake valves for forty days after the 2012 High Park Fire, at least a month the first summer after the CPF, and at least four times since then. Social and ecological disturbance cascades are not limited to the burn perimeter of the wildfire, and different geographies are subject to particular hazards over different timescales.

While residents in populous Front Range cities who rely on the Poudre River for drinking water are put at risk by the downstream effects of wildfire over time, those who live in the upper Poudre have been subject to what one geomorphologist responsible for designing much of the post-fire flood mitigation in the Poudre Canyon referred to as 'nuisance flooding.' I doubt this is how most people affected by flooding in the Poudre would characterize it, but the term is meant to indicate flooding which is not catastrophic, in contrast to the Black Hollow debris flow, for example. These smaller flooding events can still be scary and dangerous. Six inches of fast moving water can knock over an adult [@usdepartmentofcommerceTurnDonDrown]. 

Flooding in the Poudre over the summers of 2021, 2022, and 2023 impacted some of the same people again and again. One person's basement was inundated with flood waters after the force of the water broke the window, and while the mitigation work that was done helped prevent water from entering the house again, their driveway was damaged by another flooding event more than a year later. I myself was unable to leave the place I was living on several occasions over two summers until a neighbor with heavy equipment came and moved all the rock out of the way which had accumulated on my access road from flooding events. Another couple shoveled sludge deposited by flood water out of their driveway and that of their neighbor's at least twice. It was like shoveling cement, they said. Neighborhood and county roads in several places in the upper Poudre had to be repaired several times after being eroded by repeat flooding. As I write this at the end of May 2024, I received the first flash flood warning of the year for the CPF burn scar, unusually early and an indication that in the fourth summer after the fire, flooding danger continues to pose a hazard to lives, infrastructure, and watersheds. This signifies that both social and ecological disturbances persist, that as long as the watersheds in the Poudre Canyon continue to be affected by a disturbance cascade, so will its people.

## Discussion

As part of understanding, and anticipating, the complex ways ecological and social disturbances exist in relation to each other following a wildfire, and in order to better assist in community recovery, we need more creative strategies. We need strategies which center people within the context of disturbance cascades linked to wildfire as much as watersheds, or rather which consider people as part of an integrated set of human and other human relations. In an assessment of the social and economic impacts from the 2002 Hayman Fire, which held the status of Colorado’s largest wildfire for eighteen years, a suggestion emerged from a series of post-fire interviews for the existence of a ‘national, interagency, rehabilitation coordinator’ [@kentSocialEconomicIssues2003, p. 386] to facilitate communication with the public and between agencies like the USFS and the NRCS to coordinate recovery efforts on private and public lands. Twenty-two years after the Hayman Fire, nothing like this has materialized.

I propose a modification of an ecological assessment following wildfires on USFS lands that could provide a helpful template for considering social-ecological disturbances over time. A team of specialists from the USFS across multiple resource areas, such as soil and watershed scientists, fire and forest ecologists, botanists, and archeologists, conduct what is called a Burned Area Emergency Assessment (BAER) following larger or more severe wildfires. The first assessment is done as soon as possible after or during a wildfire, in areas it has already passed through. The team uses a combination of rapid assessment tools, models, and professional judgement to assess threats to critical values on USFS lands as a result of the wildfire and determine a set of treatment options.

A soil scientist and BAER Program Coordinator with the USFS in Colorado explained to me that these 'critical values on forest system lands are obviously just a subset of all values and concerns in the post-wildfire environment.' Because some information collected by the BAER team is at a watershed scale, however, even though it is only conducted on USFS lands, it is collected in coordination with and can be utilized by county level emergency managers, municipal water providers, the state transportation department, and the USGS, among others. By way of example, the USGS makes a map and spatial data available to the public of preliminary debris flow hazard assessments at the drainage-basin scale using some information produced by the BAER team, such as field-validated soil burn severity data. This is some of the earliest and most accessible publicly available data to help private landowners determine their level of exposure to flooding or debris flows. My own family relied on the assessment published by the USGS in 2020 for the CPF to determine that it was unsafe to rebuild in the same location. Sometimes the BAER assessments occur over phases, although they are designed to be done as soon as possible after a wildfire.

I propose that, perhaps under the purview of a national, interagency rehabilitation coordinator, we draw on those aspects of BAER which might be relevant for assessing the combined social-ecological impacts following a wildfire. Rather than a team of specialists solely from the USFS and with expertise only in ecology, geology, fire, and archeology, each wildfire could be assigned a cross-jurisdictional team representing broader interests and land ownership, including quantitative and qualitative social scientists and a representative from the local fire district. The team’s explicit mission could be to gather information on and analyze social-ecological disturbances as part of a connected system, with the responsibility of conducting phased assessments and recommending recovery strategies over a timescale which accounts for the social-ecological disturbance cascade over a number of years. The existence of such a team would help remove artificial boundaries which currently exist between wildfire and post-fire watershed management and between these ecological phenomena and the impacts they have on people’s lives. Such a team would provide continuity, and accountability, to people and jurisdictions affected by wildfires during a bewildering and difficult time. Support for such an initiative would require federal funding and possibly the creation of new legislation. To this end, there is recognition of the difficulty of managing wildfire at the federal level by the USFS in the recently published Wildfire Crisis Strategy [@forestserviceConfrontingWildfireCrisis2022] and by legislators in the form of funding allocated toward addressing wildfire challenges through the Bipartisan Infrastructure Law and the Inflation Reduction Act. Given this and the extraordinary wildfire and climate change challenges communities and governments are facing across the world, it would benefit us all to pursue innovative strategies for living with, and recovering from, wildfire.

In this paper, I suggest that mobilizing the concept of a disturbance cascade which links social and ecological systems disrupted by wildfire expands our capacity for evaluating the social impacts of wildfire as a social-ecological disturbance cascade, both immediately following wildfires and over time. Ecological disturbance theory recognizes the complexity of how ecosystems respond to disturbances over different timescales [@gaiserLongTermEcologicalResearch2020]. In the American West, flooding and debris flows are a known element in the wildfire disturbance cascade and an active area of scholarly inquiry [@burnettFactorsInfluencingFlood2023; @liuGuidanceParameterizingPostfire2023; @graberHowLongRunoffGenerated2023]. Conceptualizing wildfire as dual disturbance cascades &mdash; both social and ecological &mdash; could facilitate research that examines the implications of flooding and debris flows following wildfire in a more systematic way. In turn, this would support awareness among emergency and land managers and legislators, the formation of policies which explicitly address post-fire flooding, and funding mechanisms which account for cascading hazards.

## References

<!-- # References -->
\section*{Bibliography}
\addcontentsline{toc}{section}{Bibliography} 

<!-- Reset page config. For proper referencing  -->
\noindent
\leftskip=2em
\parindent=-2em

<div id="refs"></div>